my_sql:
    enabled: false
    hostname: 'localhost'
    port: 3306
    database: 'database'
    username: 'root'
    password: ''
    useSSL: false
    pool_size: 3

# Disabling/enabling modules requires you to restart your whole server, this makes sure all events are (un)registered correctly
modules:
    sign_spy: true
    command_spy: true
    broadcast: true

im_muted:
    # When true, a command will be executed, when false a message wil be sent to the mentioned player
    execute_command: true
    # The command that the issuer will perform if the above setting is set to true
    command: "tell [target] [message]"
    # The message format when the above setting is set to false
    # use [target] to get the name of the target, use [issuer] to get the name of the player who is executing
    # the command [message] will be replaced with the message (editable in lang config)
    message: '&bFrom [issuer]: [message]'
    # When true a success message will be sent to the issuer (edit this messages in the locales)
    success_message: false

mutes:
    # A list of all commands that should be blocked when a player is muted
    # send commands containing ":", for example: "/minecraft:tell" will be seen as "/tell",
    # so if this list contains "me" the commands: "me", "minecraft:me" and "any-other-prefix:me" will be blocked
    command_blacklist:
        - 'me'
        - 'say'
        - 'tell'
        - 'whisper'
        - 'reply'
        - 'pm'
        - 'message'
        - 'msg'
        - 'emsg'
        - 'epm'
        - 'etell'
        - 'ewhisper'
        - 'w'
        - 'm'
        - 't'
        - 'r'
        - 'mail send'

formats:
    kick:
        - "&cYou have been kicked!"
        - ""
        - "&7Reason: &f[reason]"
        - "&7Find out more:&f www.example.com"
    temporarily_muted:
        - "&c———————————————————————————"
        - "&c&lHey! &cYou are still muted for [time_left]!"
        - "&7Reason: &c[reason]"
        - "&7Find out more here:&c www.example.com/faq#muted"
        - "&c———————————————————————————"
    permanently_muted:
        - "&c———————————————————————————"
        - "&c&lHey! &cYou are currently muted!"
        - "&7Reason: &c[reason]"
        - "&7Find out more here:&c www.example.com/faq#muted"
        - "&c———————————————————————————"
    temporarily_banned:
        - "&cYou are temporarily banned for &f[time_left]&c from this server!"
        - ""
        - "&7Reason: &f[reason]"
        - "&7Find out more:&e&n www.example.com"
    permanently_banned:
        - "&cYou are permanently banned from this server!"
        - ""
        - "&7Reason: &f[reason]"
        - "&7Find out more:&e&n www.example.com"
    reason_warning:
        - "&c&lWARNING"
        - "You have been warned for [reason]"
    message_warning:
        - "&c&lWARNING"
        - "[message]"

# | config generated at version ${project.version}
