# When true the issuer needs the permission "epicpunishments.templates.use.<templateName>" to use the template.
# When false you only need "epicpunishments.templates.use" + "epicpunishments.<templateType>"
requireExactTemplatePermission: false

